### ISSUE TITLE
Create Issues for: Apply Common Code Style

### ISSUE THREAD

**Issue by kyleyoung1121** [EECE3093C/team-project-wiitanks#5]
We are using GDScript style guide found here: https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

Create github issues for each repository to update all existing code to match this style guide.

**Comment by watermelonslice** [comment]
It may not be possible to use a code hook to clean up commits before they join the online repo. Apparently that's what code reviews are for, we might have to just adapt the recommended gdscript style here:

https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

**Comment by kyleyoung1121** [comment]
Good to know! Thank you for looking into that.
Luckily, after reviewing the recommended gdscript style, I am finding that this very nearly fits with my current styling.
I will create a new issue to ensure that I adapt any remaining Base Game code to fit this standard

**Comment by watermelonslice** [comment]
no yeah that sounds great, weekly code reviews would be a good thing for us to do. maybe if we meet up on fridays we can all do a code review together. turns out the gdscript style is based on the python style, so it's already familiar

**Comment by watermelonslice** [comment]
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_styleguide.html

Here's the official style guide for gdscript

**Comment by kyleyoung1121** [comment]
Closing Issue:
I have created new issues for each repository to ensure that all existing code is checked against this common code style
