### ISSUE TITLE
Research Godot Unit Testing

### ISSUE THREAD

**Issue by kyleyoung1121** [EECE3093C/team-project-wiitanks#6]
Determine how to create unit tests for existing code, within the Godot 4.0 IDE.

Report findings to this issue.

**Comment by kyleyoung1121** [comment]
Findings:

Unit Testing within Godot is possible.
There is a widely accepted industry standard for this: Godot Unit Testing library (GUT) 

By reviewing the below linked video, I have gathered the following steps to integrate GUT into our project.
https://www.youtube.com/watch?v=5DrhMiuLRl0

Setup
-Install 'Gut - Godot Unit Testing' from the Godot AssetLib
-Activate Gut Project->ProjectSettings->Plugins, select Gut and mark as Active
-Create TestRunner Scene. (new scene w/ Gut node) 
-Create Test and Unit folders in FileSystem such that: res://Test/Unit
-Navigate to TestRunner Scene -> Inspector -> Directory 1 (set this to res://Test/Unit)

Write Tests
-Create test_x.gd script, where x is something we are testing
-Modify 'extends Node' to 'extends res://addons/gut/test.gd'
-Pull in an instance of what you would like to test: 'var Character = load("res://Character.gd")'
-Create method(s) beginning with test_
-Within a test method, take some action and then assert what the outcome should be: assert_eq(health, 0, "hp should be 0")

Execute Tests
-Run TestRunner Scene
-Click the play button to run tests

**Comment by watermelonslice** [comment]
Hey Kyle, great work on researching this problem! Just wanted to add in here that I couldn't get a Gut node to appear in my palette, but since there's a panel-based test menu for gut that doesn't require any nodes, I'm going to be using that instead. I'll update once I've tried it in my repo, and if I can get testing automated through Github actions.

**Comment by kyleyoung1121** [comment]
Having reviewed this research and having made more progress in writing unit tests within Godot, I wanted to update this issue with my most recent findings, and close this research issue.

Changes from initial findings:
- Now that we are in Godot 4.0, there are no GUT Nodes. (TestRunner scene no longer required)
- To execute tests, use the bottom drawer menu to select GUT (same menu that contains the debug output)

Additional findings:
- You can use before_each() to run code before every test in a file.
- In order to create an instance of a class to test on, first call instantiate(), then _ready() on that class's scene
- To test a function that emits a signal, use class.emitted_signal.connect(please_connect_to_this_method)
